# Generated by Django 6.0.4 on 2026-04-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pr',
            new_name='Product',
        ),
    ]
