# Generated by Django 6.0.4 on 2026-05-05 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_pr_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\\\+?1?\\\\d{9,15}$')], verbose_name='Номер телефона')),
                ('message', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='Загрузите фото товара', upload_to='products/photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
