# Generated by Django 6.0.4 on 2026-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите содержимое статьи', verbose_name='Содержимое')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog_preview/photo', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блоговая запись',
                'verbose_name_plural': 'Блоговые записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
