# Generated by Django 6.0.4 on 2026-05-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_views_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views_count',
        ),
    ]
